#!/bin/bash
#
# Given a list of IP addresses, use mtr to trace to each one and then
# draw a dot file

if [ -z "$1" ]; then
    echo need ip list file
    exit 1
fi
IPLIST="$1"

# Date is quantised to most recent 10 minutes - forming a kind of cache
DATE=$(($(date +%s)/600*600))

DOT="$IPLIST-$DATE.dot"

echo "# $0 $*" >$DOT
echo "graph G {" >>$DOT

cat "$IPLIST" | while read _ip _desc; do
    ip=`echo "$_ip" | sed -e 's/#.*//'`
    desc=`echo "$_desc" | sed -e 's/#.*//'`
    if [ -z "$ip" ]; then
        continue
    fi
    echo "Trace to $ip $desc" 1>&2

    NODE_STR="\"$ip\" [color=green label=\"\\N\n$desc\"];"

    mkdir -p traces
    TRACE=traces/$DATE.$ip

    if [ ! -e "$TRACE" ]; then
        mtr --no-dns --report --report-cycles 2 --csv $ip >$TRACE
    fi

    (
    LAST=
    IFS=","
    cat $TRACE | while read m_ver m_time m_status m_host m_hop m_ip m_loss m_rest; do
        if [ "$m_ip" = "???" ]; then
            m_ip="UNK_${m_host}_${m_hop}"
        fi
        if [ -n "$LAST" ]; then
            echo "\"$LAST\" -- \"$m_ip\";"
        fi
        LAST="$m_ip"
    done
    )
done | sort | uniq >>$DOT

echo "}" >>$DOT

echo $DOT

