#!/bin/bash
#
# Given a list of IP addresses, use mtr to trace to each one and then
# draw a dot file

DOT=`tempfile -d. -s.dot`

echo "# $0 $#" >$DOT
echo "graph G {" >>$DOT

for i in $*; do
    LAST=
    mtr --no-dns --report --report-cycles 2 --csv $i | cut -d"," -f6 | while read j; do
        if [ "$j" = "???" ]; then
            LAST=
            continue
        fi
        if [ -n "$LAST" ]; then
            echo "\"$LAST\" -- \"$j\";"
        fi
        LAST="$j"
    done
done | sort | uniq >>$DOT

echo "}" >>$DOT

echo $DOT

