#!/bin/bash
#
# Given a list of IP addresses, use mtr to trace to each one and then
# draw a dot file

if [ -z "$1" ]; then
    echo need ip list file
    exit 1
fi
IPLIST="$1"

DOT=`date "+$IPLIST-%s.dot"`

echo "# $0 $#" >$DOT
echo "graph G {" >>$DOT

grep -v "^#" $IPLIST |while read ip desc; do
    if [ -z "$ip" ]; then
        continue
    fi
    echo "Trace to $ip $desc" 1>&2

    if [ -n "$desc" ]; then
        echo "\"$ip\" [label=\"\\N\n$desc\"];"
    fi

    (
    LAST=
    IFS=","
    mtr --no-dns --report --report-cycles 2 --csv $ip | while read m_ver m_time m_status m_host m_hop m_ip m_rest; do
        if [ "$m_ip" = "???" ]; then
            m_ip="UNK_${m_host}_${m_hop}"
        fi
        if [ -n "$LAST" ]; then
            echo "\"$LAST\" -- \"$m_ip\";"
        fi
        LAST="$m_ip"
    done
    )
done | sort | uniq >>$DOT

echo "}" >>$DOT

echo $DOT

